<table>
   <thead>
      <tbody>
         @foreach ($filtered_rows as $row)
            <tr>
               <td></td>
               <td></td>
               <td></td>
               <td></td>
               <td></td>
               <td></td>
               <td></td>
               <td></td>
               <td></td>
            </tr>
         @endforeach
         <tr></tr>
      </tbody>
   </thead>
</table>